target 'CYTEasyPass' do
platform :ios , '8.0'

pod 'ReactiveCocoa' , '~>2.5'
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'MJExtension','~> 3.0.13'
pod 'AFNetworking', '~> 3.1.0'
#友盟统计
pod 'UMengAnalytics-NO-IDFA', '~> 4.2.5'
pod 'Masonry' , '~>1.1.0'
pod 'MJRefresh' , '~>3.1.14.1'
pod 'IQKeyboardManager'
pod 'TTTAttributedLabel'
pod 'FBRetainCycleDetector','~> 0.1.3’
pod 'MJNIndexView', '~> 0.0.1'
pod 'FCUUID', '~> 1.3.1'
pod 'AvoidCrash', '~> 1.6.7'
#循环滚动banner
pod 'SDCycleScrollView', '~> 1.73'
#微信分享
pod 'WechatOpenSDK'
#极光推送
pod 'JPush' , '~>3.0.7'
pod 'UITextView+Placeholder'
pod 'Bugly' , '~>2.4.8'
pod 'WebViewJavascriptBridge', '~> 6.0.2'

# 以静态库(.a + Header)的方式集成，从iOS8开始支持，支持以前的老工程
pod "YCAutoTrackingSDK/Static", :git => "http://gitlab.bitautotech.com/wangshaolin/YCAutoTrackingSDK.git", :tag => "201711161728"

end
