# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://gitee.com/jentle_095/specs.git'

target 'JZToastDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'JZToast'

  target 'JZToastDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JZToastDemoUITests' do
    # Pods for testing
  end

end
